### PR TITLE
Support for node-sass v4

### PR DESCRIPTION
**Pull request by hkusulja**
Current dependency to node-sass v3 is not supported on Node v8

Tested and updated this repository, wintersmith-sassy, to support also node-sass v4 versions as dependency.

If you want to use current node-sass v3 with Node v7 or less, you still can.
This is just a feature to support newer versions.
It is tested, please approve and submit to public node packages.

### CODE REVIEW

**Comment by hkusulja** [comment]
Also, if needed, please update package.json of this repo to newever instead 1.1.0 to version": "1.1.1"

**Comment by jnordberg** [comment]
Just ran the tests with node v8.1.4, and everything passed. What exactly is your problem?

**Comment by jnordberg** [comment]
In any case, I published version 1.2.0 with node-sass 4.5 on npm now

**Comment by hkusulja** [comment]
dependancy, node-sass v3 does not support building itself on Node v8.1.4 for Windows. node-sass v4 must be used, which was not allowed by your repo package.json.
It is ok now, and resolved. Thank you very much.

**Pull request closed without merging**
