### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by hkusulja**
It does not work with node-sass 4.x.x

### CODE REVIEW

**Comment by jnordberg** [comment]
Hmm, how does this help? The ^ semver should match only v3

**Comment by hkusulja** [comment]
Yeah, but node-sass v3.x.x is very old, and not supported by Node v8
Your project, I believe, normally supports node-sass 4.x.x, but is not allowed by package.json
So please just update package.json to support node-sass v4 also, by putting the ">" instead of "^".
Thank you

**Comment by jnordberg** [comment]
Ok, not going to merge this then. I'll happily accept a PR with a (tested 😉) upgrade to node-sass 4.

**Comment by hkusulja** [comment]
I did and I do not see any issue, so please merge it.

**Pull request closed without merging**
